### ISSUE TITLE
transaction with multiple copies of key

### ISSUE THREAD

**Issue by SergejJurecko** [refuge/cowdb#4]
Adding two writes in a transaction with the same key, produces two kv pairs with the same key. 

cowdb:transact(P,[{add,a,2},{add,a,3}]).
cowdb:fold(P, fun(Got, Acc) -> {ok, [Got | Acc]} end, []).
{ok,[{a,3},{a,2}]}

A bit odd for a kv store. Is this is working as intended?

**Comment by benoitc** [comment]
Sounds odd, will check what is happening there, thanks for the issue
